### ISSUE TITLE
Apigee Integration Cloud Logging Enablement Deployment Issue

### ISSUE THREAD

**Issue by kondurure** [GoogleCloudPlatform/application-integration-management-toolkit#186] opened 2024-02-19 14:55 UTC
we are trying to enable google cloud logging in all our integrations part of project. 

We have a setting button at the top right corner of integrations where we enable the Local logging(to be updated to async mode) and under log setting Enable Cloud logging field(to be enabled)
 
![image](https://github.com/GoogleCloudPlatform/application-integration-management-toolkit/assets/106219615/77789a19-5cbb-46e2-ac7a-fa4991f774e9)

In dev since we are doing manual, its working as expected but when we are pushing the code to higher environment even though the src file has config details which is required to enable ,still post deployment it’s not getting enabled in QA

 
![image](https://github.com/GoogleCloudPlatform/application-integration-management-toolkit/assets/106219615/a5805f6b-677b-460c-9ad4-6dd3af320b1c)

**Comment by srinandan** [comment] 2024-02-20 15:45
This is a duplicate of issue #180

**Closed by srinandan** 2024-02-20 15:45 UTC
Labels: duplicate

**Comment by ssvaidyanathan** [comment] 2024-02-20 23:20
v0.74.0 should support this
